

# PERSONALIZATION
# Site variables
name: Hackers@UPC
# og: assets/img/og.png
logo: /assets/img/logo.png
original_repo: https://github.com/hackupc/hackersatupc.org
description: Hackers@UPC community and events page
ga: UA-69542332-5
domain: hackersatupc.org


# Style variables
accent_color: "#303AB2"
events_overlay_color: "#000000"
background_color: "#FAFAFA"
footer_text_color: "#000000"

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: Hackers@UPC
author-description: "Hackers@UPC is a non-profit student organization at Universitat Polit√®cnica de Catalunya. 
We organize events during the year, nationally and internationally, to promote science and technology among 
students and create a great community in the technological world. Our mission is to foster learning, designing, 
and building in order to turn student's ideas into a reality! "
email: support@hackersatupc.org
website: https://hackersatupc.org

# Social media + community variables
twitter: hackersupc
fb: hackersupc
fb-community: hackersatupc
slack: http://slack.hackersatupc.org
telegram: http://telegram.hackersatupc.org

instagram: hackersupc
youtube: HackersUPC
github-org: hackupc

# legal
legal_notice: https://hackupc.com/legal_notice/
terms_and_conditions: https://hackersatupc.org/assets/docs/HackNights_Terms_And_Conditions.pdf
privacy_and_cookies: https://hackersatupc.org/assets/docs/Privacy_And_Cookies_Policy.pdf

# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Madrid
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:+0100
  TZOFFSETTO:+0200
  TZNAME:CEST
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=4SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:+0200
  TZOFFSETTO:+0100
  TZNAME:CET
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=4SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
